### ISSUE TITLE
Missing markup tags

### ISSUE THREAD

**Issue by JakeDavidLatham** [bijx/Steam-Markup-Generator#2]
Markup tags for H2 and H3 missing, same with olist and ulist.

**Comment by bijx** [comment]
#1 adds h2 and h3, but olist and ulist are still planned features. They were a little more complicated to implement than I thought.

I'll deploy the new version in the coming days!

**Comment by bijx** [comment]
`H2` and `H3` addition branch has been deployed and can now be used in app.
